/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IOwnableSlice, IOwnableSliceInterface } from "../IOwnableSlice";

const _abi = [
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IOwnableSlice__factory {
  static readonly abi = _abi;
  static createInterface(): IOwnableSliceInterface {
    return new utils.Interface(_abi) as IOwnableSliceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IOwnableSlice {
    return new Contract(address, _abi, signerOrProvider) as IOwnableSlice;
  }
}
