/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { ISlice, ISliceInterface } from "../ISlice";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint32",
        name: "categoryIndex",
        type: "uint32",
      },
    ],
    name: "_addToSliceCategory",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "creator",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "minimumShares",
        type: "uint256",
      },
      {
        internalType: "address[]",
        name: "currencies",
        type: "address[]",
      },
      {
        internalType: "bool",
        name: "isImmutable",
        type: "bool",
      },
      {
        internalType: "bool",
        name: "isControlled",
        type: "bool",
      },
    ],
    name: "_createSlicer",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "newLogicImpl",
        type: "address",
      },
    ],
    name: "_upgradeSlicers",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "getEthUsd",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "implementation",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "address payable",
            name: "slicerAddress",
            type: "address",
          },
          {
            internalType: "uint32",
            name: "productId",
            type: "uint32",
          },
          {
            internalType: "uint16",
            name: "quantity",
            type: "uint16",
          },
          {
            internalType: "address",
            name: "currency",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "value",
            type: "uint256",
          },
        ],
        internalType: "struct PurchaseInfo[]",
        name: "purchaseInfo",
        type: "tuple[]",
      },
    ],
    name: "payProducts",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        internalType: "address[]",
        name: "slicerAddresses",
        type: "address[]",
      },
      {
        internalType: "address[]",
        name: "contractAddresses",
        type: "address[]",
      },
    ],
    name: "triggerRelease",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        internalType: "address",
        name: "contractAddress",
        type: "address",
      },
      {
        internalType: "address[]",
        name: "slicerAddresses",
        type: "address[]",
      },
    ],
    name: "unreleasedBatch",
    outputs: [
      {
        internalType: "uint256[]",
        name: "",
        type: "uint256[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class ISlice__factory {
  static readonly abi = _abi;
  static createInterface(): ISliceInterface {
    return new utils.Interface(_abi) as ISliceInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): ISlice {
    return new Contract(address, _abi, signerOrProvider) as ISlice;
  }
}
