/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IUniOps, IUniOpsInterface } from "../IUniOps";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "currency",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "weiPrice",
        type: "uint256",
      },
      {
        internalType: "int16",
        name: "twapInterval",
        type: "int16",
      },
    ],
    name: "getCurrencyPrice",
    outputs: [
      {
        internalType: "uint256",
        name: "currencyPrice",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "currency",
        type: "address",
      },
    ],
    name: "getPool",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IUniOps__factory {
  static readonly abi = _abi;
  static createInterface(): IUniOpsInterface {
    return new utils.Interface(_abi) as IUniOpsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IUniOps {
    return new Contract(address, _abi, signerOrProvider) as IUniOps;
  }
}
