/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { PriceFeeds, PriceFeedsInterface } from "../PriceFeeds";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "currency",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "weiPrice",
        type: "uint256",
      },
      {
        internalType: "int16",
        name: "twapInterval",
        type: "int16",
      },
    ],
    name: "_getCurrencyPrice",
    outputs: [
      {
        internalType: "uint256",
        name: "currencyPrice",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "currency",
        type: "address",
      },
    ],
    name: "_getPool",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class PriceFeeds__factory {
  static readonly abi = _abi;
  static createInterface(): PriceFeedsInterface {
    return new utils.Interface(_abi) as PriceFeedsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): PriceFeeds {
    return new Contract(address, _abi, signerOrProvider) as PriceFeeds;
  }
}
