/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export type PurchaseInfoStruct = {
  slicerAddress: string;
  productId: BigNumberish;
  quantity: BigNumberish;
  currency: string;
  value: BigNumberish;
};

export type PurchaseInfoStructOutput = [
  string,
  number,
  number,
  string,
  BigNumber
] & {
  slicerAddress: string;
  productId: number;
  quantity: number;
  currency: string;
  value: BigNumber;
};

export interface ISliceInterface extends utils.Interface {
  contractName: "ISlice";
  functions: {
    "_addToSliceCategory(uint32)": FunctionFragment;
    "_createSlicer(address,uint256,uint256,address[],bool,bool)": FunctionFragment;
    "_upgradeSlicers(address)": FunctionFragment;
    "getEthUsd()": FunctionFragment;
    "implementation()": FunctionFragment;
    "initialize()": FunctionFragment;
    "owner()": FunctionFragment;
    "payProducts((address,uint32,uint16,address,uint256)[])": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "triggerRelease(address,address[],address[],uint16)": FunctionFragment;
    "unreleasedBatch(address,address,address[])": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "_addToSliceCategory",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "_createSlicer",
    values: [string, BigNumberish, BigNumberish, string[], boolean, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "_upgradeSlicers",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "getEthUsd", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "implementation",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "payProducts",
    values: [PurchaseInfoStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "triggerRelease",
    values: [string, string[], string[], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "unreleasedBatch",
    values: [string, string, string[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "_addToSliceCategory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_createSlicer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_upgradeSlicers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getEthUsd", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "implementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "payProducts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "triggerRelease",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unreleasedBatch",
    data: BytesLike
  ): Result;

  events: {};
}

export interface ISlice extends BaseContract {
  contractName: "ISlice";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ISliceInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    _addToSliceCategory(
      categoryIndex: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    _createSlicer(
      creator: string,
      id: BigNumberish,
      minimumShares: BigNumberish,
      currencies: string[],
      isImmutable: boolean,
      isControlled: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    _upgradeSlicers(
      newLogicImpl: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getEthUsd(overrides?: CallOverrides): Promise<[BigNumber]>;

    implementation(overrides?: CallOverrides): Promise<[string]>;

    initialize(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    payProducts(
      purchaseInfo: PurchaseInfoStruct[],
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    triggerRelease(
      account: string,
      slicerAddresses: string[],
      contractAddresses: string[],
      slxPercentage: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    unreleasedBatch(
      account: string,
      contractAddress: string,
      slicerAddresses: string[],
      overrides?: CallOverrides
    ): Promise<[BigNumber[]]>;
  };

  _addToSliceCategory(
    categoryIndex: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  _createSlicer(
    creator: string,
    id: BigNumberish,
    minimumShares: BigNumberish,
    currencies: string[],
    isImmutable: boolean,
    isControlled: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  _upgradeSlicers(
    newLogicImpl: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getEthUsd(overrides?: CallOverrides): Promise<BigNumber>;

  implementation(overrides?: CallOverrides): Promise<string>;

  initialize(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  payProducts(
    purchaseInfo: PurchaseInfoStruct[],
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  triggerRelease(
    account: string,
    slicerAddresses: string[],
    contractAddresses: string[],
    slxPercentage: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  unreleasedBatch(
    account: string,
    contractAddress: string,
    slicerAddresses: string[],
    overrides?: CallOverrides
  ): Promise<BigNumber[]>;

  callStatic: {
    _addToSliceCategory(
      categoryIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    _createSlicer(
      creator: string,
      id: BigNumberish,
      minimumShares: BigNumberish,
      currencies: string[],
      isImmutable: boolean,
      isControlled: boolean,
      overrides?: CallOverrides
    ): Promise<string>;

    _upgradeSlicers(
      newLogicImpl: string,
      overrides?: CallOverrides
    ): Promise<void>;

    getEthUsd(overrides?: CallOverrides): Promise<BigNumber>;

    implementation(overrides?: CallOverrides): Promise<string>;

    initialize(overrides?: CallOverrides): Promise<void>;

    owner(overrides?: CallOverrides): Promise<string>;

    payProducts(
      purchaseInfo: PurchaseInfoStruct[],
      overrides?: CallOverrides
    ): Promise<void>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    triggerRelease(
      account: string,
      slicerAddresses: string[],
      contractAddresses: string[],
      slxPercentage: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    unreleasedBatch(
      account: string,
      contractAddress: string,
      slicerAddresses: string[],
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;
  };

  filters: {};

  estimateGas: {
    _addToSliceCategory(
      categoryIndex: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    _createSlicer(
      creator: string,
      id: BigNumberish,
      minimumShares: BigNumberish,
      currencies: string[],
      isImmutable: boolean,
      isControlled: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    _upgradeSlicers(
      newLogicImpl: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getEthUsd(overrides?: CallOverrides): Promise<BigNumber>;

    implementation(overrides?: CallOverrides): Promise<BigNumber>;

    initialize(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    payProducts(
      purchaseInfo: PurchaseInfoStruct[],
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    triggerRelease(
      account: string,
      slicerAddresses: string[],
      contractAddresses: string[],
      slxPercentage: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    unreleasedBatch(
      account: string,
      contractAddress: string,
      slicerAddresses: string[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    _addToSliceCategory(
      categoryIndex: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    _createSlicer(
      creator: string,
      id: BigNumberish,
      minimumShares: BigNumberish,
      currencies: string[],
      isImmutable: boolean,
      isControlled: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    _upgradeSlicers(
      newLogicImpl: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getEthUsd(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    implementation(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    initialize(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    payProducts(
      purchaseInfo: PurchaseInfoStruct[],
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    triggerRelease(
      account: string,
      slicerAddresses: string[],
      contractAddresses: string[],
      slxPercentage: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    unreleasedBatch(
      account: string,
      contractAddress: string,
      slicerAddresses: string[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
