/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface PriceOpsInterface extends utils.Interface {
  contractName: "PriceOps";
  functions: {
    "_getCurrencyPrice(address,uint256,int16)": FunctionFragment;
    "_getPool(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "_getCurrencyPrice",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "_getPool", values: [string]): string;

  decodeFunctionResult(
    functionFragment: "_getCurrencyPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "_getPool", data: BytesLike): Result;

  events: {};
}

export interface PriceOps extends BaseContract {
  contractName: "PriceOps";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: PriceOpsInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    _getCurrencyPrice(
      currency: string,
      weiPrice: BigNumberish,
      twapInterval: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { currencyPrice: BigNumber }>;

    _getPool(currency: string, overrides?: CallOverrides): Promise<[string]>;
  };

  _getCurrencyPrice(
    currency: string,
    weiPrice: BigNumberish,
    twapInterval: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  _getPool(currency: string, overrides?: CallOverrides): Promise<string>;

  callStatic: {
    _getCurrencyPrice(
      currency: string,
      weiPrice: BigNumberish,
      twapInterval: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    _getPool(currency: string, overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    _getCurrencyPrice(
      currency: string,
      weiPrice: BigNumberish,
      twapInterval: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    _getPool(currency: string, overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    _getCurrencyPrice(
      currency: string,
      weiPrice: BigNumberish,
      twapInterval: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    _getPool(
      currency: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
