/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface SlicerProductsProdInterface extends utils.Interface {
  contractName: "SlicerProductsProd";
  functions: {
    "isProduct(uint32)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "isProduct",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "isProduct", data: BytesLike): Result;

  events: {
    "ProductAdded(uint32,uint32,uint256,bool,bool,bool,uint32,address,bytes,uint256[],uint32[])": EventFragment;
    "ProductCategoryChanged(uint32,uint32)": EventFragment;
    "ProductCurrencyChanged(uint32,uint256,bool)": EventFragment;
    "ProductInfoChanged(uint32,bool,uint32,uint256)": EventFragment;
    "ProductPaid(address,uint32,uint16,uint256)": EventFragment;
    "ProductRemoved(uint32)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ProductAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ProductCategoryChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ProductCurrencyChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ProductInfoChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ProductPaid"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ProductRemoved"): EventFragment;
}

export type ProductAddedEvent = TypedEvent<
  [
    number,
    number,
    BigNumber,
    boolean,
    boolean,
    boolean,
    number,
    string,
    string,
    BigNumber[],
    number[]
  ],
  {
    productId: number;
    categoryIndex: number;
    price: BigNumber;
    isUSD: boolean;
    isMultiple: boolean;
    isInfinite: boolean;
    availableUnits: number;
    creator: string;
    data: string;
    subSlicersId: BigNumber[];
    subProducts: number[];
  }
>;

export type ProductAddedEventFilter = TypedEventFilter<ProductAddedEvent>;

export type ProductCategoryChangedEvent = TypedEvent<
  [number, number],
  { productId: number; categoryIndex: number }
>;

export type ProductCategoryChangedEventFilter =
  TypedEventFilter<ProductCategoryChangedEvent>;

export type ProductCurrencyChangedEvent = TypedEvent<
  [number, BigNumber, boolean],
  { productId: number; productPrice: BigNumber; isUSD: boolean }
>;

export type ProductCurrencyChangedEventFilter =
  TypedEventFilter<ProductCurrencyChangedEvent>;

export type ProductInfoChangedEvent = TypedEvent<
  [number, boolean, number, BigNumber],
  {
    productId: number;
    isInfinite: boolean;
    units: number;
    productPrice: BigNumber;
  }
>;

export type ProductInfoChangedEventFilter =
  TypedEventFilter<ProductInfoChangedEvent>;

export type ProductPaidEvent = TypedEvent<
  [string, number, number, BigNumber],
  { from: string; productId: number; quantity: number; productPrice: BigNumber }
>;

export type ProductPaidEventFilter = TypedEventFilter<ProductPaidEvent>;

export type ProductRemovedEvent = TypedEvent<[number], { productId: number }>;

export type ProductRemovedEventFilter = TypedEventFilter<ProductRemovedEvent>;

export interface SlicerProductsProd extends BaseContract {
  contractName: "SlicerProductsProd";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: SlicerProductsProdInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    isProduct(
      productId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[void]>;
  };

  isProduct(productId: BigNumberish, overrides?: CallOverrides): Promise<void>;

  callStatic: {
    isProduct(
      productId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "ProductAdded(uint32,uint32,uint256,bool,bool,bool,uint32,address,bytes,uint256[],uint32[])"(
      productId?: BigNumberish | null,
      categoryIndex?: BigNumberish | null,
      price?: null,
      isUSD?: null,
      isMultiple?: null,
      isInfinite?: null,
      availableUnits?: null,
      creator?: string | null,
      data?: null,
      subSlicersId?: null,
      subProducts?: null
    ): ProductAddedEventFilter;
    ProductAdded(
      productId?: BigNumberish | null,
      categoryIndex?: BigNumberish | null,
      price?: null,
      isUSD?: null,
      isMultiple?: null,
      isInfinite?: null,
      availableUnits?: null,
      creator?: string | null,
      data?: null,
      subSlicersId?: null,
      subProducts?: null
    ): ProductAddedEventFilter;

    "ProductCategoryChanged(uint32,uint32)"(
      productId?: BigNumberish | null,
      categoryIndex?: null
    ): ProductCategoryChangedEventFilter;
    ProductCategoryChanged(
      productId?: BigNumberish | null,
      categoryIndex?: null
    ): ProductCategoryChangedEventFilter;

    "ProductCurrencyChanged(uint32,uint256,bool)"(
      productId?: BigNumberish | null,
      productPrice?: null,
      isUSD?: null
    ): ProductCurrencyChangedEventFilter;
    ProductCurrencyChanged(
      productId?: BigNumberish | null,
      productPrice?: null,
      isUSD?: null
    ): ProductCurrencyChangedEventFilter;

    "ProductInfoChanged(uint32,bool,uint32,uint256)"(
      productId?: BigNumberish | null,
      isInfinite?: null,
      units?: null,
      productPrice?: null
    ): ProductInfoChangedEventFilter;
    ProductInfoChanged(
      productId?: BigNumberish | null,
      isInfinite?: null,
      units?: null,
      productPrice?: null
    ): ProductInfoChangedEventFilter;

    "ProductPaid(address,uint32,uint16,uint256)"(
      from?: string | null,
      productId?: BigNumberish | null,
      quantity?: null,
      productPrice?: null
    ): ProductPaidEventFilter;
    ProductPaid(
      from?: string | null,
      productId?: BigNumberish | null,
      quantity?: null,
      productPrice?: null
    ): ProductPaidEventFilter;

    "ProductRemoved(uint32)"(
      productId?: BigNumberish | null
    ): ProductRemovedEventFilter;
    ProductRemoved(productId?: BigNumberish | null): ProductRemovedEventFilter;
  };

  estimateGas: {
    isProduct(
      productId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    isProduct(
      productId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
